name: Prepare data (PSP 2025)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: prepare-data
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show manual/psp2025
        run: |
          ls -al manual || true
          ls -al manual/psp2025 || true

      - name: Assert CSV inputs exist
        run: |
          test -f manual/psp2025/pst4.csv   || { echo "::error file=manual/psp2025/pst4.csv::Missing"; exit 1; }
          test -f manual/psp2025/pst4p.csv  || { echo "::error file=manual/psp2025/pst4p.csv::Missing"; exit 1; }
          # parties je volitelné, ale doporučené (pro názvy stran)

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: |
          npm i

      - name: Generate results JSON (PSP 2025)
        env:
          TARGETS: ${{ secrets.TARGETS }} # např. 554821:545911
        run: node scripts/generate-results-psp2025.js

      - name: Commit public/data/*
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(data): update public/data (PSP 2025)"
          file_pattern: public/data/**
