name: Prepare data (PSP 2025)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: prepare-data-psp2025
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (no LFS needed)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug secrets presence
        run: |
          echo "TARGETS_PSP2025=${{ secrets.TARGETS_PSP2025 && 'present' || 'MISSING' }}"
          echo "OKRSKY_2025_GEOJSON_URL=${{ secrets.OKRSKY_2025_GEOJSON_URL && 'present' || 'MISSING' }}"

      - name: Verify CSV inputs exist
        run: |
          set -e
          for f in manual/psp2025/pst4.csv manual/psp2025/pst4p.csv manual/psp2025/cns.csv; do
            [ -f "$f" ] || { echo "::error file=$f::Missing file"; exit 1; }
            sz=$(stat -c%s "$f")
            [ "$sz" -gt 1000 ] || { echo "::error file=$f::File too small ($sz B)"; exit 1; }
          done
          echo "All CSV inputs present."

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm i; fi

      - name: Generate PSP 2025 results JSON
        env:
          TARGETS_PSP2025: ${{ secrets.TARGETS_PSP2025 }}
        run: node scripts/generate-results-psp2025.js

      - name: Commit generated /public/data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(data): update PSP 2025 public/data"
          file_pattern: public/data/**
